### ISSUE TITLE
Choose folder/ files button doesn't work

### ISSUE THREAD

**Issue by Biasio** [e-caste/study-planner#39]
Ciao!
I have installed your program in linux with the dev instructions, because the release page file is not working for me, in terminal it says:
`Language detected: en
Segmentation fault (core dumped)`
after executing it.
With dev instructions I'm able to start main.py and the dark mode button works just fine, but for the next one (choose folder etc) doesn't open any window. Maybe I have done something wrong?
I'm on Pop_OS! 22.04 if it helps.
Thank you for your time

**Comment by e-caste** [comment]
Hi @Biasio and thanks for your interest in this project. A couple of things come to mind:
1. have you installed the `libmediainfo-dev` package with `apt`? By the way, if it has changed with Ubuntu 22.04 let me know and I'll update the README, right now it's for 20.04
2. since you can run the `main.py` script from the terminal, would you be so kind as to comment with the Python traceback?

**Comment by e-caste** [comment]
@Biasio 
Here's what I've found so far:
- implicit requirements to develop on Linux (Ubuntu 22.04) include `gcc` and `libxcb-xinerama0` -- I'll see if I can find a way to include the latter inside the executable
- the traceback that you are (probably) seeing is the following and is due to using the wrong Python version (3.10, while the expected one is 3.9) -- I will look into making it compatible with 3.10:
```
Language detected: en
Already on latest release.
Traceback (most recent call last):
  File ".../study-planner/main.py", line 128, in <lambda>
    self.choose_directory_button.clicked.connect(lambda: show_file_dialog())
  File ".../study-planner/main.py", line 115, in show_file_dialog
    FileDialog(last_dir=get_preference(Preference.last_dir,
  File ".../study-planner/main.py", line 221, in __init__
    self.setLayout(LoadingScreen(show_spinner=False))
  File ".../study-planner/main.py", line 148, in __init__
    self.loading_spinner = QtWaitingSpinner()
  File ".../study-planner/waiting_spinner_widget.py", line 60, in __init__
    self.updateTimer()
  File ".../study-planner/waiting_spinner_widget.py", line 188, in updateTimer
    self._timer.setInterval(1000 / (self._numberOfLines * self._revolutionsPerSecond))
TypeError: setInterval(self, int): argument 1 has unexpected type 'float'
```
This doesn't yet answer why the executable crashes since it bundles Python 3.9, so I will keep this issue open, but in the meantime you can use Python 3.9: https://askubuntu.com/a/682875
