### ISSUE TITLE
Fix PyInstaller error at runtime

### ISSUE THREAD

**Issue by e-caste** [e-caste/study-planner#8]
```
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 144, in __init__
  File "ctypes/__init__.py", line 369, in __init__
OSError: dlopen(libmediainfo.dylib, 6): image not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 29, in <lambda>
  File "main.py", line 41, in show_file_dialog
  File "main.py", line 48, in __init__
  File "main.py", line 53, in show_result_widget
  File "main.py", line 86, in __init__
  File "main.py", line 108, in get_analysis
  File "backend.py", line 45, in get_result
  File "backend.py", line 38, in get_total_video_seconds
  File "backend.py", line 38, in <genexpr>
  File "pymediainfo/__init__.py", line 306, in parse
  File "pymediainfo/__init__.py", line 197, in _get_library
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 146, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll 'libmediainfo.dylib'. Most probably this dynlib/dll was not found when the application was frozen.
```

**Comment by e-caste** [comment]
The fix: add to the `pyinstaller` command the argument `--add-binary 'venv/lib/python3.6/site-packages/pymediainfo/libmediainfo.0.dylib:.'`.
